model:
  embedding_dim: 8
  deep_dims: [128, 64]
  cross_layers: 3
  dropout: 0.3

training:
  batch_size: 256
  epochs: 10
  learning_rate: 0.001
  random_seed: 42

servig:
  model_name: dcn_v2
  port: 3000